export default {
  cloud: true,
  pages: [
    'pages/index/index',
    'pages/record/index',
    'pages/chat/index',
    'pages/data/index',
    'pages/mine/index',
    'pages/onboarding/index',
    'pages/protein-recommend/index',
    'pages/protein-confirm/index',
    'pages/protein-complete/index',
    'pages/action-flow/index',
    'pages/action-complete/index',
    'pages/plan/index',
    'pages/share/index',
    'pages/settings/index',
    'pages/quick-log/index',
    'pages/weather/index',
    'pages/reminder/index',
    'pages/goal/index',
  ],
  window: {
    navigationStyle: 'custom',
    backgroundColor: '#F8FAF7',
    navigationBarBackgroundColor: '#F8FAF7',
    navigationBarTextStyle: 'black',
    navigationBarTitleText: '食律',
  },
}
